url: http://bglug.it
baseurl: /scuole

# Site settings
title: BgLUG Scuole
email: info@bglug.it
description: "Il progetto 'Linux va a scuola' di Bergamo Linux Users Group (BgLUG) aiuta le scuole a migrare a Linux."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e6960a
  secondary: dc910a
  secondary-dark: 333

# Team names, titles and social links

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/bglug_it
  - title: facebook
    url: https://it-it.facebook.com/bglug
  - title: github
    url: https://github.com/bglug-it

# Postal address (add as many lines as necessary)
address:
  - line: Bergamo Linux Users Group (bglug.it)

# Build settings
markdown: kramdown
permalink: pretty
